### ISSUE TITLE
Add new dependances for cake layer Evolution

### ISSUE THREAD

**Issue by reyman** [openmole/mgo#4]
Actually Evolution component is defined like this

``` scala
trait Evolution extends Termination
    with Lambda
    with G
    with F
    with P
    with Archive
    with Breeding
    with Elitism { self =>
```

It seems an evolution metaheuristic also need   :
- a mapping function between Genotype and Phenotype, it can be used to define different sort of problem resolution :  `genome -> simulation`, `genome -> mathematical function`  
- objective functions, the actual `evaluation()` function defined in Problem Class

A proposition ?

``` scala
trait Evolution extends Termination
    with Lambda
    with G
    with F
    with P
    with Archive
    with Breeding
    with Elitism 
    with GtoPmapping
    with ObjectiveFunctions { self =>
```

**Comment by romainreuillon** [comment]
Complete re-factoring make that request obsolete.
