### ISSUE TITLE
Publish version for scala 2.12

### ISSUE THREAD

**Issue by ylaurent** [openmole/mgo#5]
Hello,
I wanted to try out mgo, looks awesome, is it possible to publish a version for scala 2.12 ?
thanks 👍

**Comment by romainreuillon** [comment]
Hello, I just published MGO 2.2 for scala 2.11 and 2.12 on sonatype.

**Comment by ylaurent** [comment]
awesome! thanks :)

**Comment by ylaurent** [comment]
it seems this a required (at least projectseptemberinc) otherwise sbt can't find the dependencies.
resolvers += Resolver.sonatypeRepo("public")
resolvers += Resolver.sonatypeRepo("snapshots")
resolvers += Resolver.bintrayRepo("projectseptemberinc", "maven")
It might be worth adding it to the README :)

**Comment by romainreuillon** [comment]
Yes thanks!
